name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Setup do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias do backend
        working-directory: backend
        run: npm ci

      - name: Instalar dependencias do frontend
        working-directory: frontend
        run: npm ci

      - name: Build do frontend
        working-directory: frontend
        run: npm run build

      - name: Testes do backend
        working-directory: backend
        run: npm test